### ISSUE TITLE
Decrease the number of third-party dependencies

### ISSUE THREAD

**Issue by Atrate** [bcranton/goldengoblet.net#15]
I am of course in no position to make requests, but it would be nice if the website didn't depend so heavily on third-party resources:

- boostrapcdn
- jsdelivr
- jquery
- cloudfront
- googlesyndication

Also, thanks for making the guuldaan goblet website, man!

**Comment by bcranton** [comment]
Unfortunately, these dependencies are required for the website to have the look and feel it does now. For some of them, I admittedly could use local copies instead of importing them from a CDN. However, that would only serve to use more of my limited bandwidth I receive from Netlify, even if only by a tiny amount. 

To go over them each:
boostrapcdn, jsdelivr, and jquery are all from Bootstrap. They provide things like the styling for most elements (the tables are the most obvious example, but really every thing is affected by this). The javascript bits are mostly required for dropdown menu functionality. 
These three dependencies specifically could be replaced with local copies if I desired, however, I don't particularly see the benefit.

cloudfront is actually put in after the website is deployed from Netlify. It replaces my images with compressed lossless versions, which helps me save on the amount of bandwidth I am using.

googlesyndication is actually Google Adsense. This month I have blown past my free 100GB of bandwidth from Netlify, and am being charged for additional bandwidth. Hence why googlesyndication is in there, as I intend to experiment with a small ad on the page in hopes of offsetting the cost of added bandwidth.

Hopefully that gives a better idea of what each piece is doing, and explains why I am using them the way I currently am.

**Comment by bcranton** [comment]
Update: I slept on this over night, and decided not to run ads. I don't want to try to monetize something that I made for fun for the community.
So, googlesyndication has been removed
